services:
  tournament-server:
    build: ./brackets-manager-server
    container_name: brackets-manager-api
    ports:
      - "3000:3000"
    volumes:
      - ./brackets-manager-server/db.json:/app/db.json
    restart: unless-stopped
    networks:
      - smash-net

  ssbu_matchups:
    image: ghcr.io/juniornff/ssbu-matchups-tracker:latest
    container_name: Ssbu_Matchups
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./pass.txt:/app/pass.txt
    environment:
      - API_TORNEOS_URL=http://tournament-server:3000
    depends_on:
      - tournament-server
    networks:
      - smash-net

networks:
  smash-net:
    driver: bridge