services:
  tournament-server:
    image: ghcr.io/juniornff/brackets-manager-server:latest
    container_name: brackets-manager-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - API_KEY=${API_KEY}
      - DATA_FILE=db.json
      - VERBOSE=false
    networks:
      - smash-net

  ssbu_matchups:
    image: ghcr.io/juniornff/ssbu-matchups-tracker:latest
    container_name: Ssbu_Matchups
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - COMUNITY_NAME=${COMUNITY_NAME}
      - API_TORNEOS_URL=http://tournament-server:3000
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - tournament-server
    networks:
      - smash-net

networks:
  smash-net:
    driver: bridge